#!/usr/bin/env ruby

require 'json'
require 'yaml'

path = File.absolute_path(ARGV.shift)

puts "Merging reports from #{path}"
main_report_file = path + "/main_rspec_report.json"
main_report = JSON.load_file(main_report_file)
new_report = main_report.dup
Dir.glob(path + "/rspec_node_*").each do |report_file|
  report = JSON.load_file(report_file)

  # Remove existing values
  updates = report.delete_if do |key, value|
    main_report[key] && main_report[key] == value
  end
  new_report.merge!(updates)

  puts "\tMerged #{report_file} adding #{updates.size} results."
end

File.write(main_report_file, JSON.pretty_generate(new_report))
puts "\tSaved #{main_report_file}."
