danger.import_dangerfile(path: 'scripts/support/metadata')
danger.import_dangerfile(path: 'scripts/support/software')
danger.import_dangerfile(path: 'scripts/support/specs')
danger.import_dangerfile(path: 'scripts/support/template')
danger.import_dangerfile(path: 'scripts/support/changelog')
danger.import_dangerfile(path: 'scripts/support/reviewers')
