NO_NEW_SPEC_MESSAGE = <<~MSG.freeze
You've made some changes in the cookbooks, but didn't add any tests.
That's OK as long as you're refactoring existing code,
but please consider adding the ~backstage label in that case.
MSG

has_app_changes = !git.modified_files.grep(%r{\A(files|lib)/}).empty?
has_spec_changes = !git.modified_files.grep(/spec/).empty?

warn NO_NEW_SPEC_MESSAGE, sticky: false if has_app_changes && !has_spec_changes
