#!/bin/bash

set -x

# Fix GitLab permissions
if id -u git; then
	# Fix data storage
	chown -R git:git /var/opt/gitlab/.ssh
	chown -R git:git /var/opt/gitlab/.gitconfig
	chown -R git:git /var/opt/gitlab/git-data
	chown -R git:git /var/opt/gitlab/gitlab-ci/builds
	chown -R git:git /var/opt/gitlab/gitlab-rails
	chown -R git:git /var/opt/gitlab/gitlab-shell
	chown -R git:gitlab-www /var/opt/gitlab/gitlab-workhorse

	# Fix log storage
	chown git /var/opt/gitlab/gitlab-workhorse
	chown git /var/log/gitlab/gitlab-rails
	chown git /var/log/gitlab/gitlab-shell
	chown git /var/log/gitlab/sidekiq
	chown git /var/log/gitlab/unicorn
	chown gitlab-psql /var/log/gitlab/postgresql
	chown gitlab-redis /var/log/gitlab/redis

	# Update log files
	chown -R git:git /var/log/gitlab/gitlab-rails/*.log
	chown -R git:git /var/log/gitlab/gitlab-shell/*.log
	chown -R git:git /var/log/gitlab/unicorn/*.log
fi

# Fix nginx buffering directory permission
if id -u gitlab-www; then
	chown -R gitlab-www:gitlab-www /var/opt/gitlab/nginx/*_temp
	chown -R gitlab-www:gitlab-www /var/opt/gitlab/nginx/*_cache
fi

# Fix database storage
if id -u gitlab-psql; then
	chown -R gitlab-psql:gitlab-psql /var/opt/gitlab/postgresql
fi

# Fix redis storage
if id -u gitlab-redis; then
	chown -R gitlab-redis:gitlab-redis /var/opt/gitlab/redis
fi

# Fix registry storage
if id -u registry; then
    chown -R registry:registry /var/opt/gitlab/gitlab-rails/shared/registry
fi
