#!/usr/bin/env python

import glob
import os

files = ["bundler.rb",
         "bzip2.rb",
         "cacerts.rb",
         "chef-gem.rb",
         "chef-zero.rb",
         "config_guess.rb",
         "curl.rb",
         "git.rb",
         "gitlab-config-template.rb",
         "gitlab-cookbooks.rb",
         "gitlab-ctl.rb",
         "gitlab-pages.rb",
         "gitlab-psql.rb",
         "gitlab-rails.rb",
         "gitlab-scripts.rb",
         "gitlab-selinux.rb",
         "gitlab-shell.rb",
         "gitlab-workhorse.rb",
         "jemalloc.rb",
         "krb5.rb",
         "libedit.rb",
         "libffi.rb",
         "libiconv.rb",
         "libicu.rb",
         "liblzma.rb",
         "libossp-uuid.rb",
         "libtool.rb",
         "libxml2.rb",
         "libxslt.rb",
         "libyaml.rb",
         "logrotate.rb",
         "makedepend.rb",
         "mattermost.rb",
         "mixlib-log.rb",
         "mysql-client.rb",
         "ncurses.rb",
         "nginx.rb",
         "nodejs.rb",
         "ohai.rb",
         "omnibus-ctl.rb",
         "openssl.rb",
         "pcre.rb",
         "pkg-config-lite.rb",
         "popt.rb",
         "postgresql.rb",
         "postgresql_new.rb",
         "python-docutils.rb",
         "python3.rb",
         "rb-readline.rb",
         "readline.rb",
         "redis.rb",
         "registry.rb",
         "remote-syslog.rb",
         "rsync.rb",
         "ruby.rb",
         "rubygems.rb",
         "runit.rb",
         "unzip.rb",
         "util-macros.rb",
         "xproto.rb",
         "zlib.rb"]

for f in glob.glob("*.rb"):
    if f not in files:
        os.remove(f)
