#!/bin/sh

# Sleep a bit to avoid going nuts after gitlab just started.
sleep ${pre_sleep}

nice /opt/gitlab/embedded/sbin/logrotate -s ${dir}/logrotate.status logrotate.conf

# Sleep some more. After this, the script exits to be restarted by Runit.
sleep ${post_sleep}
