stages:
  - package

variables:
  # BUILDER_IMAGE_REGISTRY is incorrectly passed from parent pipeline due to
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29069. Hence we are
  # hardcoding the dev registry for SLES jobs.
  DEV_BUILDER_IMAGE_REGISTRY: 'dev.gitlab.org:5005/cookbooks/gitlab-omnibus-builder'

.ee-tag-only: &ee-tag-only
  rules:
    # SLES job might not have connection to RMT server to install additional packages
    # FIPS packages won't necessarily work in a non-fips environment
    - if: '$deploy_instance == "true"'
      when: never
    - if: '$CI_COMMIT_TAG =~ /^.*ee\.\d.*$/'

.ce-tag-only: &ce-tag-only
  rules:
    # RPi packages are not uploaded to pre-release repo.
    - if: '$deploy_instance == "true"'
      when: never
    - if: '$CI_COMMIT_TAG =~ /^.*ce\.\d.*$/'

.distribution-amd64-tags:
  - distribution-runner
  - amd64

.distribution-arm64-tags:
  - distribution-runner
  - arm64

.distribution-armhf-tags:
  - distribution-runner
  - armhf

before_script:
  - bash scripts/ci/prepare_bundle.sh

.job_base: &job_base
  stage: package
  script:
    - bash scripts/ci/install_package.sh
    - bash scripts/ci/deploy_package.sh
  tags: !reference [.distribution-amd64-tags]
  retry: 2

.apt-install: &apt-install
  extends: .job_base
  variables:
    package_type: deb
    package_manager: apt

.yum-install: &yum-install
  extends: .job_base
  variables:
    package_type: rpm
    package_manager: yum

.zypper-install: &zypper-install
  extends: .job_base
  variables:
    package_type: rpm
    package_manager: zypper

.apt-arm-install: &apt-arm-install
  extends: .apt-install
  tags: !reference [.distribution-arm64-tags]

.yum-arm-install: &yum-arm-install
  extends: .yum-install
  tags: !reference [.distribution-arm64-tags]

.zypper-arm-install: &zypper-arm-install
  extends: .zypper-install
  tags: !reference [.distribution-arm64-tags]

# apt based
Ubuntu-18.04-check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_18.04:latest"
  extends: .apt-install
Ubuntu-20.04-check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_20.04:latest"
  extends: .apt-install
Ubuntu-20.04-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_20.04_arm64:latest"
  extends: .apt-arm-install
Ubuntu-22.04-check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_22.04:latest"
  extends: .apt-install
Ubuntu-22.04-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_22.04_arm64:latest"
  extends: .apt-arm-install
Debian-10-check:
  image: "${BUILDER_IMAGE_REGISTRY}/debian_10:latest"
  extends: .apt-install
Debian-10-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/debian_10_arm64:latest"
  extends: .apt-arm-install
Debian-11-check:
  image: "${BUILDER_IMAGE_REGISTRY}/debian_11:latest"
  extends: .apt-install
Debian-11-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/debian_11_arm64:latest"
  extends: .apt-arm-install
Debian-12-check:
  image: "${BUILDER_IMAGE_REGISTRY}/debian_12:latest"
  extends: .apt-install
Debian-12-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/debian_12_arm64:latest"
  extends: .apt-arm-install
Raspberry-Pi-2-Buster-check:
  image: "${BUILDER_IMAGE_REGISTRY}/rpi_10:latest"
  extends:
    - .apt-install
    - .ce-tag-only
  variables:
    package_repository: 'raspberry-pi2'
  tags: !reference [.distribution-armhf-tags]
Raspberry-Pi-2-Bullseye-check:
  image: "${BUILDER_IMAGE_REGISTRY}/rpi_11:latest"
  extends:
    - .apt-install
    - .ce-tag-only
  variables:
    package_repository: 'raspberry-pi2'
  tags: !reference [.distribution-armhf-tags]
Ubuntu-18.04-fips-check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_18.04_fips:latest"
  extends:
    - .apt-install
    - .ee-tag-only
  variables:
    USE_SYSTEM_SSL: "true"
Ubuntu-20.04-fips-check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_20.04_fips:latest"
  extends:
    - .apt-install
    - .ee-tag-only
  variables:
    USE_SYSTEM_SSL: "true"

# yum based
CentOS-7-check:
  image: "${BUILDER_IMAGE_REGISTRY}/centos_7:latest"
  extends: .yum-install
AlmaLinux-8-check:
  image: "${BUILDER_IMAGE_REGISTRY}/almalinux_8:latest"
  extends: .yum-install
AlmaLinux-8-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/almalinux_8_arm64:latest"
  extends: .yum-arm-install
AlmaLinux-9-check:
  image: "${BUILDER_IMAGE_REGISTRY}/almalinux_9:latest"
  extends: .yum-install
AlmaLinux-9-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/almalinux_9_arm64:latest"
  extends: .yum-arm-install
AmazonLinux-2-check:
  image: "${BUILDER_IMAGE_REGISTRY}/amazonlinux_2:latest"
  extends: .yum-install
AmazonLinux-2-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/amazonlinux_2_arm64:latest"
  extends: .yum-arm-install
AmazonLinux-2023-check:
  image: "${BUILDER_IMAGE_REGISTRY}/amazonlinux_2023:latest"
  extends: .yum-install
AmazonLinux-2023-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/amazonlinux_2023_arm64:latest"
  extends: .yum-arm-install
AlmaLinux-8-fips-check:
  image: "${BUILDER_IMAGE_REGISTRY}/almalinux_8_fips:latest"
  extends:
    - .yum-install
    - .ee-tag-only
  variables:
    USE_SYSTEM_SSL: "true"
AmazonLinux-2-fips-check:
  image: "${BUILDER_IMAGE_REGISTRY}/amazonlinux_2_fips:latest"
  extends:
    - .yum-install
    - .ee-tag-only
  variables:
    USE_SYSTEM_SSL: "true"

# zypper based
OpenSUSE-15.5-check:
  image: "${BUILDER_IMAGE_REGISTRY}/opensuse_15.5:latest"
  extends: .zypper-install
OpenSUSE-15.5-arm64-check:
  image: "${BUILDER_IMAGE_REGISTRY}/opensuse_15.5_arm64:latest"
  extends: .zypper-arm-install
SLES-12.5-check:
  image: "${DEV_BUILDER_IMAGE_REGISTRY}/sles_12sp5:latest"
  extends:
    - .zypper-install
    - .ee-tag-only
SLES-15.2-check:
  image: "${DEV_BUILDER_IMAGE_REGISTRY}/sles_15sp2:latest"
  extends:
    - .zypper-install
    - .ee-tag-only
