### For services that need a docker daemon

.dind:
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_MIRROR: "https://mirror.gcr.io"
    DOCKER_OPTIONS: "--registry-mirror ${DOCKER_MIRROR}"
  services:
    - name: ${DOCKER_DIND_IMAGE}
      alias: docker
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_OPTIONS" ]
