# Vault integration configuration for accessing Group Access Tokens
# Reference: doc/build/vault_integration.md
# Template for jobs that need access to private repositories
.with-build-token:
  extends: .vault-integration
  secrets:
    ALTERNATIVE_PRIVATE_TOKEN:
      file: false
      vault: access_tokens/gitlab-com/gitlab-org/security/_group_access_tokens/build-token/token@ci