#!/bin/bash
#
# Perform necessary gitlab setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

for command in gitlab-ctl gitlab-rake gitlab-rails gitlab-ci-rake gitlab-ci-rails
do
  ln -sf /opt/gitlab/bin/$command /usr/bin || error_exit "Could not symlink $command in /usr/bin"
done

# Try collecting fqdn if it is set correctly
fqdn=$(/bin/hostname -f)
if [[ ! -z ${fqdn} ]]; then
  external_url="http://${fqdn}"
else
  external_url="http://gitlab.example.com"
fi

# Create a minimal gitlab.rb template if /etc/gitlab/gitlab.rb does not exist.
if ! [ -e /etc/gitlab/gitlab.rb ] ; then
  mkdir -p /etc/gitlab
  cp /opt/gitlab/etc/gitlab.rb.template /etc/gitlab/gitlab.rb
  sed -i 's!GENERATED_EXTERNAL_URL!'$external_url'!g' /etc/gitlab/gitlab.rb
  chmod 600 /etc/gitlab/gitlab.rb
fi

if [ -x /usr/bin/dpkg-query ] ; then
  # We are in the land of .deb packages. We should fix package directory owners
  # because of the faulty 7.2.0 / 7.2.1 .deb packages.
  /usr/bin/dpkg-query -L gitlab | while read f ; do
    if [ -d "$f" ] ; then
      # This directory may have been created when installing omnibus-gitlab
      # 7.2.0 / 7.2.1, so it could have the wrong owner.
      chown root:root "$f"
    fi
  done
fi

# Perform automatic migrations in case of an upgrade. Will exit without doing
# anything if this is fresh install.
/opt/gitlab/bin/gitlab-ctl upgrade

echo "Thank you for installing GitLab!"
echo "Configure and start GitLab by running the following command:"
echo
echo "sudo gitlab-ctl reconfigure"
echo
echo "GitLab should be reachable at ${external_url}"
echo "Otherwise configure GitLab for your system by editing /etc/gitlab/gitlab.rb file"
echo "And running reconfigure again."
echo
echo "For a comprehensive list of configuration options please see the Omnibus GitLab readme"
echo "https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md"
echo

exit 0
