#!/bin/bash
#
# Perform necessary gitlab setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

for command in gitlab-ctl gitlab-rake gitlab-rails
do
  ln -sf /opt/gitlab/bin/$command /usr/bin || error_exit "Could not symlink $command in /usr/bin"
done

echo "Thank you for installing GitLab!"
echo "You can configure GitLab for your system by running the following command:"
echo
echo "sudo gitlab-ctl reconfigure"
echo

exit 0
