CURRENT_PATH = File.expand_path(File.dirname(__FILE__))
file_cache_path "#{CURRENT_PATH}/cache"
cookbook_path CURRENT_PATH
verbose_logging false
ssl_verify_mode :verify_peer
# Omnibus-GitLab only needs to know very little about the system it is running
# on. We want to disable as many Ohai plugins as we can to avoid plugin bugs
# and speed up 'gitlab-ctl reconfigure'.
#
# The list below, based on Ohai 7.4.1, is a blacklist. UNcomment a plugin to
# disable it. For example, ':Groovy,' is uncommented because omnibus-gitlab
# does not care about Groovy.
Ohai::Config[:disabled_plugins] = [
:Azure,
#:Chef,
:Cloud,
:CloudV2,
#:Command,
#:C,
#:DMI,
:EC2,
:Erlang,
:Eucalyptus,
:GCE,
:Groovy,
#:Hostname,
#:InitPackage,
#:IpScopes,
:Java,
:Joyent,
#:Kernel,
#:Keys,
#:Languages,
:Linode,
:Lua,
:Mono,
#:NetworkListeners,
#:NetworkAddresses,
:Nodejs,
#:Ohai,
#:OhaiTime,
:Openstack,
#:OS,
#:Passwd,
#:Perl,
:PHP,
#:Platform,
:Powershell,
#:PS,
#:Python,
#:Rackspace,
#:RootGroup,
#:Ruby,
#:SSHHostKey,
#:Uptime,
#:VirtualizationInfo,
#:CPU,
#:Filesystem,
#:Kernel,
#:Memory,
#:Network,
#:Platform,
#:Uptime,
#:CPU,
#:Filesystem,
#:Memory,
#:Network,
#:Platform,
#:SystemProfile,
#:CPU,
#:Filesystem,
#:Memory,
#:Network,
#:OS,
#:Platform,
#:Virtualization,
#:BlockDevice,
#:CPU,
#:Filesystem,
#:LSB,
#:Mdadm,
#:Memory,
#:Network,
#:Platform,
#:Virtualization,
#:CPU,
#:Filesystem,
#:Memory,
#:Network,
#:Platform,
#:Virtualization,
#:CPU,
#:Filesystem,
#:Memory,
#:Network,
#:Platform,
#:Virtualization,
#:CPU,
#:Filesystem,
#:Memory,
#:Network,
#:NetworkRoutes,
#:Platform,
#:CPU,
#:DMI,
#:Filesystem,
#:Memory,
#:Network,
#:Platform,
#:Virtualization,
#:Zpools,
#:CPU,
#:Filesystem,
#:Network,
#:Platform,
]
