RUBY_UPGRADE_MESSAGE = <<~MSG.freeze
This merge request is updating the Ruby version.

Please make sure this merge request follows all standards established
within the [Ruby upgrade guidelines](https://docs.gitlab.com/ee/development/ruby_upgrade.html).
MSG

lines = helper.changed_lines("config/software/ruby.rb")

warn format(RUBY_UPGRADE_MESSAGE) if lines.any? { |line| line =~ /[+-]+.*default_version/ }
