# rubocop:disable Style/SignalException

require 'yaml'

NO_CHANGELOG_LABELS = [
  'documentation',
  'tooling',
  'tooling::pipelines',
  'tooling::workflow',
  'ci-build',
  'meta'
].freeze

SEE_DOC = "See [the documentation](https://docs.gitlab.com/ee/development/changelog.html).".freeze
CREATE_CHANGELOG_MESSAGE = <<~MSG.freeze
You can create one with:

```
scripts/changelog -m %<mr_iid>s "%<mr_title>s"
```

If your merge request doesn't warrant a CHANGELOG entry,
consider adding any of the %<labels>s labels.
#{SEE_DOC}
MSG

def ee?
  ENV['CI_PROJECT_NAME'] == 'gitlab-ee' || File.exist?('../../CHANGELOG-EE.md')
end

def ee_changelog?(changelog_path)
  changelog_path =~ /unreleased-ee/
end

def ce_port_changelog?(changelog_path)
  ee? && !ee_changelog?(changelog_path)
end

def check_changelog(path)
  yaml = YAML.safe_load(File.read(path))

  fail "`title` should be set, in #{gitlab.html_link(path)}! #{SEE_DOC}" if yaml["title"].nil?
  fail "`type` should be set, in #{gitlab.html_link(path)}! #{SEE_DOC}" if yaml["type"].nil?

  if yaml["merge_request"].nil?
    message "Consider setting `merge_request` to #{gitlab.mr_json["iid"]} in #{gitlab.html_link(path)}. #{SEE_DOC}"
  elsif yaml["merge_request"] != gitlab.mr_json["iid"] && !ce_port_changelog?(path)
    fail "Merge request ID was not set to #{gitlab.mr_json["iid"]}! #{SEE_DOC}"
  end
rescue Psych::SyntaxError, Psych::DisallowedClass, Psych::BadAlias
  # YAML could not be parsed, fail the build.
  fail "#{gitlab.html_link(path)} isn't valid YAML! #{SEE_DOC}"
rescue StandardError => e
  warn "There was a problem trying to check the Changelog. Exception: #{e.name} - #{e.message}"
end

def presented_no_changelog_labels
  NO_CHANGELOG_LABELS.map { |label| %(~"#{label}") }.join(', ')
end

changelog_needed = (gitlab.mr_labels & NO_CHANGELOG_LABELS).empty?
changelog_found = git.added_files.find { |path| path =~ %r{\A(ee/)?(changelogs/unreleased)(-ee)?/} }

mr_title = gitlab.mr_json["title"].gsub(/^WIP: */, '')

if git.modified_files.include?("CHANGELOG.md")
  fail "**CHANGELOG.md was edited.** Please remove the additions and create a CHANGELOG entry.\n\n" +
    format(CREATE_CHANGELOG_MESSAGE, mr_iid: gitlab.mr_json["iid"], mr_title: mr_title, labels: presented_no_changelog_labels)
end

if changelog_needed
  if changelog_found
    check_changelog(changelog_found)
  else
    warn "**[CHANGELOG missing](https://docs.gitlab.com/ee/development/changelog.html).**\n\n" +
      format(CREATE_CHANGELOG_MESSAGE, mr_iid: gitlab.mr_json["iid"], mr_title: mr_title, labels: presented_no_changelog_labels)
  end

  message(<<~MSG)
    We are currently testing a new approach for generating changelogs. If one or
    more of your commits warrant a changelog entry, please add the appropriate
    `Changelog:` Git trailer to these commits. For example:

    ```
    Add a new awesome feature

    Here are the details about the feature being added.

    Changelog: added
    ```

    For more information, please take look at [this
    issue](https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1551).

    Note: If you have created a changelog yaml file already, please do not delete it. In the first iteration of this approach, we are using both the yaml file and Git trailer.
  MSG
end
